apiVersion: apps/v1
kind: Deployment
metadata:
  name: destiny-api
  labels:
    app: destiny-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: destiny-api
  template:
    metadata:
      labels:
        app: destiny-api
    spec:
      containers:
      - name: destiny-api
        image: your-registry/destiny-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: destiny-api
  labels:
    app: destiny-api
spec:
  selector:
    app: destiny-api
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
