apiVersion: apps/v1
kind: Deployment
metadata:
  name: destiny-web
  labels:
    app: destiny-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: destiny-web
  template:
    metadata:
      labels:
        app: destiny-web
    spec:
      containers:
      - name: destiny-web
        image: your-registry/destiny-web:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "https://your-api-domain.sealos.run"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: destiny-web
  labels:
    app: destiny-web
spec:
  selector:
    app: destiny-web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: destiny-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - your-web-domain.sealos.run
    secretName: destiny-web-tls
  rules:
  - host: your-web-domain.sealos.run
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: destiny-web
            port:
              number: 80
